Repository julia-vscode/StaticLint.jl, pull requests merged in 2020-05, with the labels that each got.

#155 check for redef of !=
  src/linting/checks.jl
  test/runtests.jl
Labels: enhancement

#156 Add some diagnostics
  src/StaticLint.jl
  src/exception_types.jl
  src/server.jl
Labels: bug

#138 Remove setpath
  README.md
  docs/src/index.md
  src/server.jl
Labels: enhancement

#157 don't try to call joinpath on nothing
  src/server.jl
Labels: bug

#158 add resolve_ref_from_module
  src/references.jl
Labels: bug

#151 Enable missing ref errors for getfields
  Project.toml
  src/linting/checks.jl
  src/references.jl
  test/runtests.jl
Labels: enhancement, ver bump required

#119 Add check for unused function arguments
  src/linting/checks.jl
  test/runtests.jl
Labels: enhancement, ver bump required

#153 Add constructor for LintOptions that coalesces nothing
  src/linting/checks.jl
  test/runtests.jl
Labels: enhancement

#160 turn checks on by default, add missingref options
  src/linting/checks.jl
  src/references.jl
Labels: bug, ver bump required

#166 Fix datatype declaration check
  src/bindings.jl
  src/linting/checks.jl
  src/references.jl
  src/type_inf.jl
  src/utils.jl
  test/runtests.jl
Labels: bug

#173 Ensure we follow VarRefs to the object they point at
  src/bindings.jl
  src/linting/checks.jl
  src/macros.jl
  src/references.jl
  src/utils.jl
  test/runtests.jl
Labels: bug

#164 Add rudimentary handling for `@eval`
  src/imports.jl
  src/linting/checks.jl
  src/macros.jl
  src/references.jl
  src/utils.jl
  test/runtests.jl
Labels: bug, enhancement

#174 Misc fixes
  src/bindings.jl
  src/imports.jl
  src/linting/checks.jl
  src/utils.jl
  test/runtests.jl
Labels: bug

#179 Bug fixes: method overloading, import/exports, add macro handler
  src/StaticLint.jl
  src/bindings.jl
  src/imports.jl
  src/linting/checks.jl
  src/macros.jl
  src/references.jl
  src/scope.jl
  src/server.jl
  src/utils.jl
  test/runtests.jl
Labels: bug

#182 symbol lookup fixes
  src/imports.jl
Labels: bug
