Repository julia-vscode/StaticLint.jl, pull requests merged in 2021-01, with the labels that each got.

#227 adapt to julia-vscode/SymbolServer.jl#194
  .github/workflows/jlpkgbutler-ci-master-workflow.yml
  .github/workflows/jlpkgbutler-ci-pr-workflow.yml
  Project.toml
  src/StaticLint.jl
Labels: Showstopper, bug

#203 Cst compat
  Project.toml
  README.md
  docs/src/index.md
  src/StaticLint.jl
  src/bindings.jl
  src/imports.jl
  src/linting/checks.jl
  src/macros.jl
  src/references.jl
  src/scope.jl
  src/server.jl
  src/type_inf.jl
  src/utils.jl
  test/runtests.jl
Labels: enhancement

#233 handle `Base.@kwdef`
  src/bindings.jl
  test/runtests.jl
Labels: bug

#234 infer binding types by use
  src/StaticLint.jl
  src/linting/checks.jl
  src/server.jl
  src/type_inf.jl
  test/runtests.jl
Labels: enhancement

#238 fix out of bounds access attempt
  src/type_inf.jl
Labels: bug

#240 ensure lookup of VarRef when resolving import blocks
  src/imports.jl
Labels: bug

#237 add eval method that isn't Core.eval
  src/scope.jl
  test/runtests.jl
Labels: bug

#239 add external functions
  src/StaticLint.jl
  src/bindings.jl
  src/interface.jl
  test/runtests.jl
Labels: enhancement

#241 check module has name
  src/imports.jl
Labels: bug

#242 remove use of Expr
  src/scope.jl
Labels: bug

#243 add resolve only pass
  Project.toml
  src/StaticLint.jl
  src/server.jl
  test/runtests.jl
Labels: enhancement

#248 Remove between Binding linkages
  src/StaticLint.jl
  src/bindings.jl
  src/imports.jl
  src/linting/checks.jl
  src/macros.jl
  src/references.jl
  src/scope.jl
  src/server.jl
  src/type_inf.jl
  src/utils.jl
  test/runtests.jl
Labels: enhancement

#250 Fix some bugs, improve type inference, a bit of a tidy
  src/linting/checks.jl
  src/type_inf.jl
Labels: bug

#252 be more careful when trying to resolve export statements early
  src/references.jl
Labels: bug
